# Generated by Django 5.2.13 on 2026-04-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='payouts_led_merchan_31a74c_idx',
            old_name='payouts_led_merchan_871057_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='payouts_led_payout__d7f5c9_idx',
            old_name='payouts_led_payout__815d18_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_status_0e8e83_idx',
            old_name='payouts_pay_status_4ab9ca_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_merchan_e714be_idx',
            old_name='payouts_pay_merchan_40a61d_idx',
        ),
    ]
